### ISSUE TITLE
Build fails on 5.15 after net/ipx.h has been removed from the kernel source

### ISSUE THREAD

**Issue by project-administrator** [lwfinger/rtl8192cu#10]
Build fails with: 
```
/var/lib/dkms/rtl8192cu/1.0/build/core/rtw_br_ext.c:25:10: fatal error: net/ipx.h: No such file or directory
   25 | #include <net/ipx.h>
```
IPX has been removed from the kernel source:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/include/net?id=6c9b40844751ea30c72f7a2f92f4d704bc6b2927

Would be nice to get IPX removed (or disabled) in the driver.

**Comment by lwfinger** [comment]
Now fixed. Do a 'git pull' and you should be good.
