### ISSUE TITLE
Do you consider fixing rtl8192ce driver?

### ISSUE THREAD

**Issue by msdos03** [lwfinger/rtl8192cu#11]
RTL8192CE driver in rtlwifi is very bad. The signal is weak and most of the channels are unusable. AP mode is not usable too. So I found the rtl871x driver of rtl8192ce and create a repo. I modified it to run it on latest linux versions. But only WEXT interface works and I can't make cfg80211 interface work. If possible, please offer some help. Thanks
https://github.com/msdos03/rtl8192ce-fixes

**Comment by lwfinger** [comment]
Adding the cfg80211 interface to one of Realtek's standard drivers, other than rtlwifi versions, is extremely difficult. I have no interest in participating in such a project.

**Comment by msdos03** [comment]
Can you help me test a patch of rtlwifi? I am going to send it to kernel. How can I contact you?

**Comment by lwfinger** [comment]
Read the kernel instructions on creating a patch. Then send it to linux-wireless@vger.kernel.org. You can attach it here if you want me to test it.

**Comment by msdos03** [comment]
I can't make the patch display correctly here. So here is the link to it.
https://github.com/msdos03/openwrt-avanta/blob/40f67393816e524cc4e4143403df7a9096e735d2/package/kernel/mac80211/patches/rtl/481-disable_txpower_from_eprom.patch
This patch can solve some low txpower problems. EEPROM on some realtek chips sets txpower to a very low level, can't be controlled manually. This patch enables users to control it manually. I have only tested it on rtl8192ce.

**Comment by msdos03** [comment]
Are you testing now? I think I should sign your name on the commit message if you test it.

**Comment by msdos03** [comment]
Do you have rtl8192ce and rtl8192cu? Please set them to ap mode and test the connection speed, remember to set txpower to the highest level. Then apply my patch and test them again. I can't even connect to the rtl8192ce ap without the patch. But nobody else uses rtl8192ce as an ap and tell their problems. rtl8192cu is also helpful to locate the problem because they use some common code.

**Comment by lwfinger** [comment]
Yes, I have samples of all the chips in rtlwifi.

My problem with your patch is that it disables the adaptive power adjustments for ALL the chips in ALL configurations. If you want to be able to freeze the power in AP mode for rtl8192ce, then you make your change when the 8192ce goes into AP mode, and reverse it when the chip leaves AP mode. I am currently chasing a problem on a different chip that crashes the user's computer. That has high priority.

**Comment by msdos03** [comment]
I realize my mistake. Now I'm not sure if this problem exists in all rtl8192ce chips. I only see one person have the same problem. If this isn't a common problem, I will add a module parameter.

**Comment by msdos03** [comment]
It looks like only one antenna is at low power level. If I put my phone directly on that antenna, I can ping the ap.

**Comment by lwfinger** [comment]
You misunderstood my point. Your patch would disable adaptive power for rtl8188ee, rtl8192ce, rtl8192cu, rtl8192de, rtl8192ee, rtl8192se, rtl8723ae, rtl8723be, AND rtl8821ae. I do not think that is what you intended.

Module parameters are not looked on with great favor. I doubt that you would get approval to create a new one.

**Comment by msdos03** [comment]
If I'm sure this is a problem in every rtl8192ce, then I should disable this option for rtl8192ce only. But I'm not sure yet. So I need you to test. I guess this is not a common problem. if this is true, module parameter is a better option.

**Comment by msdos03** [comment]
Do you know what this option exactly is? Does it read a fixed power level from eeprom?

**Comment by lwfinger** [comment]
I do not know. I am busy with a driver that does not work at all, which I find to have higher priority.
