### ISSUE TITLE
Why is this repo maintained for kernels where it appeared in upstream?

### ISSUE THREAD

**Issue by mikhailnov** [lwfinger/rtl8192cu#13]
Hello!
Could you please explain (probably even in README) why this repo is maintained for newer kernels, e.g. 5.10 and 5.15, where it exists in upstream?
Is it made just for convinience or maybe there are other reasons?

**Comment by lwfinger** [comment]
It is a different driver from the one in the kernel. If you looked at the code, the differences are obvious.

The in-kernel driver sometimes does not work, thus an alternative is provided.

**Comment by mikhailnov** [comment]
Thanks!
